CREATE TABLE [Users]
(
	[Id] BIGINT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	[UserName] NVARCHAR(200) NOT NULL,
	[Password] NVARCHAR(255) NOT NULL,

	[Deleted] BIT NOT NULL DEFAULT 0,
	[UpdateDate] DATETIME2 NULL,
	[CreateDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO

CREATE TABLE [Apis]
(
	[Id] BIGINT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	[Name] NVARCHAR(200) NOT NULL,
	[PublicKey] NVARCHAR(200) NULL,
	[PrivateKey] NVARCHAR(200) NULL,

	[Deleted] BIT NOT NULL DEFAULT 0,
	[UpdateDate] DATETIME2 NULL,
	[CreateDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO

CREATE TABLE [UserApis]
(
	[Id] BIGINT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	[UserId] BIGINT NULL FOREIGN KEY REFERENCES [Users]([Id]),
	[ApiId] BIGINT NULL FOREIGN KEY REFERENCES [Apis]([Id]),

	[Deleted] BIT NOT NULL DEFAULT 0,
	[UpdateDate] DATETIME2 NULL,
	[CreateDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO