#----------------------------------------------------------------------------------
#                                                                                  |
# If you want to run or debug some clients or services you need to first make the  |
# environment ready because they have some dependencies like MongoDB, Redis, etc.  |
#                                                                                  |
# Just run the below command through CLI and then the environment is ready:        |
#                                                                                  |
# ...> docker-compose -f Infrastucture.yml up -d            |
#                                                                                  |
# For more informition go to releated the documentation on GitHub:                 |
#                                                                                  |
# https://github.com/hamed-shirbandi/TaskoMask/wiki/Development-Setup              |
#----------------------------------------------------------------------------------

version: '3.4'

services:
  sql:
    container_name: sql
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    environment:
        SA_PASSWORD: "qwerty12345"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql:/var/opt/mssql/data 

volumes:
  sql:

